[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"

# Cache static assets aggressively
[[headers]]
  for = "/**/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/**/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/**/*.{png,jpg,jpeg,webp,svg,gif,ico,woff,woff2,ttf,eot}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Make HTML/pages always fresh
[[headers]]
  for = "/**/*.html"
  [headers.values]
    Cache-Control = "no-cache"
